dist: precise
language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g jest jest-cli
  - lsb_release -a
script:
  - webpack -p
  # - npm run build
  # - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION