dist: precise
language: node_js
node_js:
  - "6.0.0"
skip_cleanup: true
before_install:
  - lsb_release -a
script:
  - webpack -p
  # - npm run build
  # - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION