language: node_js
node_js:
  - "stable"
before_install:
 - npm install -g create-react-app
 - npm install -g jest jest-cli
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION